/**
 * Type definitions for the agent memory system.
 *
 * These types define the data structures used for storing and retrieving
 * code chunks in the memory database.
 */

/**
 * Represents a chunk of code or content stored in memory.
 *
 * Chunks are typically portions of files that have been indexed
 * for semantic search and retrieval.
 */
export interface MemoryChunk {
  /** Unique identifier for the chunk (auto-generated by database) */
  id?: number;
  /** Absolute path to the source file */
  filePath: string;
  /** Starting line number in the source file (1-indexed) */
  startLine?: number;
  /** Ending line number in the source file (1-indexed) */
  endLine?: number;
  /** The actual content of the chunk */
  content: string;
  /** Hash of the content for change detection */
  contentHash?: string;
  /** Hierarchical headers/context for this chunk (e.g., class name, function name) */
  headers?: string[];
  /** Vector embedding for semantic search */
  embedding?: Float32Array;
  /** Timestamp when the chunk was created */
  createdAt?: Date;
  /** Timestamp when the chunk was last updated */
  updatedAt?: Date;
}

/**
 * Result from a memory search operation.
 */
export interface SearchResult {
  /** The matching chunk */
  chunk: MemoryChunk;
  /** Relevance score (higher is better) */
  score: number;
  /** Snippet of matched content with highlighting (for keyword search) */
  snippet?: string;
}

/**
 * Options for inserting a chunk into memory.
 */
export interface InsertChunkOptions {
  /** Whether to update if a chunk with the same file_path and content_hash exists */
  upsert?: boolean;
}

/**
 * Options for search operations.
 */
export interface SearchOptions {
  /** Maximum number of results to return */
  limit?: number;
  /** Minimum score threshold for results */
  minScore?: number;
  /** Filter results to specific file paths (glob patterns supported) */
  filePathFilter?: string;
}
